// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL11gMn1BcmhLKdiZpAWFzQoU1YZ-N1zQ',
    appId: '1:618772577889:web:06519f3251b6fc011f3420',
    messagingSenderId: '618772577889',
    projectId: 'aquazen-a44c3',
    authDomain: 'aquazen-a44c3.firebaseapp.com',
    storageBucket: 'aquazen-a44c3.firebasestorage.app',
    measurementId: 'G-0NBBX3YF48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJYE6cAf9mEtWkJb6glzO6VPIxcR1vqvk',
    appId: '1:618772577889:android:89060f13fbcdcf701f3420',
    messagingSenderId: '618772577889',
    projectId: 'aquazen-a44c3',
    storageBucket: 'aquazen-a44c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_E6KUjAG24sKq3uFPaTKDUddY3ET77PQ',
    appId: '1:618772577889:ios:007a2301481eeb181f3420',
    messagingSenderId: '618772577889',
    projectId: 'aquazen-a44c3',
    storageBucket: 'aquazen-a44c3.firebasestorage.app',
    iosBundleId: 'com.example.aquazenfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_E6KUjAG24sKq3uFPaTKDUddY3ET77PQ',
    appId: '1:618772577889:ios:007a2301481eeb181f3420',
    messagingSenderId: '618772577889',
    projectId: 'aquazen-a44c3',
    storageBucket: 'aquazen-a44c3.firebasestorage.app',
    iosBundleId: 'com.example.aquazenfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL11gMn1BcmhLKdiZpAWFzQoU1YZ-N1zQ',
    appId: '1:618772577889:web:68a3369d3b68b2b51f3420',
    messagingSenderId: '618772577889',
    projectId: 'aquazen-a44c3',
    authDomain: 'aquazen-a44c3.firebaseapp.com',
    storageBucket: 'aquazen-a44c3.firebasestorage.app',
    measurementId: 'G-XL69WHJYGJ',
  );
}